user = runwait("whoami")
user = trim(user[0])
path = cat("export NSCRIPT_PATH=/home/",user,"/nscript")
run(path)
bashrc = cat("/home/",user,"/.bashrc")
njh::save("#nscript path",path,bashrc)
print("Nscript path ",path,"g")
